server:
  port: 8090
  
spring:           
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   
          filters:
          - StripPrefix=1   
      routes:
      - id: ignore
        uri: no://op
        order: -1
        predicates:
        - Path=*/internal/*, /*/*/internal/**,/*/*/*/internal/**,/*/actuator/*        
       
logging.file: /var/log/${spring.application.name}.log              
logging:
  file: 
    max-size: 10MB  
    max-history: 2    
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: warn   
    org.springframework.*: trace
