server:
  port: 8761
  forward-headers-strategy: native

eureka:
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}    
    
logging:
  file: /var/log/${spring.application.name}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: error 